# Generated by Django 4.2.5 on 2023-09-23 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_description',
        ),
    ]
