# Generated by Django 4.2.5 on 2023-09-25 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_question_options_alter_registration_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='response',
            name='partner1',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='response',
            name='partner2',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
