# Generated by Django 4.2.5 on 2023-09-25 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_question_category_question_question_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_category',
            name='negative_mark_to',
            field=models.CharField(choices=[('M', 'For Me'), ('O', 'Opposite')], default='M', max_length=1),
        ),
    ]
