# Generated by Django 4.2.5 on 2023-09-25 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_alter_question_category_negative_mark_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question_category',
            name='negative_mark_to',
            field=models.CharField(choices=[('TM', 'To Me'), ('TO', 'To Opposite')], default='TM', max_length=2),
        ),
    ]
