# Generated by Django 4.2.5 on 2023-09-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0008_remove_question_category_negative_mark_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='questions',
            field=models.ManyToManyField(to='game.question'),
        ),
    ]
