# Generated by Django 4.2.5 on 2023-09-26 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0009_registration_questions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='questions',
            field=models.ManyToManyField(blank=True, null=True, to='game.question'),
        ),
    ]
