# Generated by Django 4.2.5 on 2023-09-26 12:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('game', '0011_remove_registration_gender_remove_registration_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='partner2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partner2', to=settings.AUTH_USER_MODEL),
        ),
    ]
