# Generated by Django 4.2.5 on 2023-09-26 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_alter_registration_partner2'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
