# Generated by Django 4.2.5 on 2023-09-27 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_registration_is_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ('id',)},
        ),
        migrations.AlterField(
            model_name='option',
            name='description',
            field=models.TextField(),
        ),
    ]
