# Generated by Django 4.2.5 on 2023-09-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0014_alter_registration_options_alter_option_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='online_count',
            field=models.BigIntegerField(default=0),
        ),
    ]
