# Generated by Django 4.2.5 on 2023-10-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0015_registration_online_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='game_round',
            field=models.BigIntegerField(default=1),
        ),
    ]
